name: Deploy Frontend Only

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      # ❌ REMOVE setup-node (not needed for static site)
      # - uses: actions/setup-node@v4

      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./frontend

      - uses: actions/deploy-pages@v4
